# Generated by Django 5.0.3 on 2024-04-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registro',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Usuario')),
                ('nombrecompleto', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('nombreusuario', models.CharField(max_length=100, verbose_name='Nombre de Usuario')),
                ('correoelectronico', models.CharField(max_length=100, verbose_name='Correo Electrónico')),
                ('claveusuario', models.CharField(max_length=40, null=True, verbose_name='Contraseña')),
                ('fechanacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('direcciondespacho', models.CharField(blank=True, max_length=200, null=True, verbose_name='Direccion de despacho')),
            ],
        ),
        migrations.AlterField(
            model_name='juego',
            name='nombre',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nombre'),
        ),
    ]
